### ISSUE TITLE
Can't access message information in get_reward() and is_done() 

### ISSUE THREAD

**Issue by kurshakuz** [aidudezzz/deepbots#32]
Hi! Firstly, I would like to say thanks for work you have done! It's very pleasing to work with the framework you created.

During development I have faced one issue and hope you can help me solve it. The problem is that I am not able access message information in get_reward() and is_done() methods of the Supervisor. The main motivation is that I need sensor readings from my robot to shape a reward and stop the episode (ex. when laserscan readings shows a very close obstacle). 
`supervisor.step([selectedAction])` returns the observations in a required way, but when I call `self.get_observations()` inside either get_reward() and is_done(), I am not able to read a message sent by an agent (`self.handle_receiver()` returns None) . I am sure, I am missing some important design feature and hope you can help me with that.

**Comment by tsampazk** [comment]
Hello, thank you for your kind words! :)

The communication scheme used in Webots, means that for every simulation step a message is broadcasted and a message is received when using one robot and one supervisor. Calling `handle_receiver()` again during the same step (1st call in regular `get_observations()` from `step()`, 2nd call - your call - inside `get_reward()`) it returns `None` because it already consumed the message broadcasted by the robot and there are no new messages.

I would suggest using an extra parameter in the class e.g. `self.observations`, where you save the latest observation received (this can be done inside `get_observations()`) and can then use it freely inside `get_reward()` or `is_done()`.

You can see this in action in [the tutorial](https://github.com/aidudezzz/deepbots-tutorials/blob/master/cartPoleTutorial/full_project/controllers/supervisorController/supervisorController.py#L16) with the `self.messageReceived` variable and as far as i can tell it is exactly the same use-case as yours. Notice that wherever it is used (e.g. in `is_done()`) it is enclosed in `if not None` blocks.

Also note that in the near future we will add a `RobotSupervisor` class that forgoes all the emitter-receiver stuff and runs RL on a single controller. [See here.](https://github.com/aidudezzz/deepbots/issues/26)

**Comment by kurshakuz** [comment]
@tsampazk thank you for suggestion, that definitely makes much more sense! I will take further updates into account too, and hope to see them soon)
