### ISSUE TITLE
Question: how to get kinect camera information

### ISSUE THREAD

**Issue by ZY-KK** [aidudezzz/deepbots#88]
I try to combined a panda robot with a kinect camera. The figure is camera definition. I try to run script of the panda demo, even I attach the camera, the webots simulator did not show image. Could you please tell me how can I get image from kinect camera and show on webots simulator if I use deepbots framework.

![Screenshot-20210402103028-287x504](https://user-images.githubusercontent.com/25016163/113401198-af9e2600-93ab-11eb-8914-a8612e7fa741.png)

![image](https://user-images.githubusercontent.com/25016163/113401433-00158380-93ac-11eb-98f3-193c22e10ea4.png)

**Comment by ManosMagnus** [comment]
Could you please share a sample code in order to test it?

**Comment by ZY-KK** [comment]
For example, I try to modify your demo of panda robot and attach a kinect camera, but I do not know how can I get the image from kinect camera. sorry that there is no such sample code, I would like to know if it has method or interface to get image(color and depth)

**Comment by ManosMagnus** [comment]
I will check it ASAP. Thank you!

**Comment by tsampazk** [comment]
@ZY-KK Hello, i am not able to test it right now, but i would suggest to first make sure that the camera is visible by checking the various options at the menu bar on top. Then try to move or resize the camera window because sometimes there are multiple windows open that overlap and hide one another! Those would be the first two steps i would do before trying any other more complicated solution. 

However if you cannot resolve the issue i would suggest to ask the webots developers directly as they are more knowledgeable about issues like this. You can open an issue on their repository or post a question in their discord channel, which i think will be the best.

For getting images in code, there's a wealth of information in the webots documentation to get images from cameras.

**Comment by ZY-KK** [comment]
@tsampazk thanks for your reply. I'll try. Another question I would like to ask is that how can I know some internal method information, for example, I import RobotSupervisor from deepbots, but I don't know what function it has, so, where can I find detail documentation of deepbots?

**Comment by ManosMagnus** [comment]
I will recommend to take a look on the following tutorials:

- [Emitter Receiver scheme tutorial](https://github.com/aidudezzz/deepbots-tutorials/tree/master/emitterReceiverSchemeTutorial)
- [Robot supervisor scheme tutorial](https://github.com/aidudezzz/deepbots-tutorials/tree/master/robotSupervisorSchemeTutorial)

As well as on the following Pull Request:

-  [deepbots-panda to deepworlds](https://github.com/aidudezzz/deepworlds/pull/33)

**Comment by KelvinYang0320** [comment]
I have combined [webots camera](https://cyberbotics.com/doc/reference/camera) with deepbots in this [deepbots-inverseRL](https://github.com/KelvinYang0320/deepbots-inverseRL).
**This is an incomplete project** (just an example of camera with deepbots).
I am still working on inverse RL part.
Hope this helps:smiley:
